### ISSUE TITLE
Home-Assistant 0.113.0

### ISSUE THREAD

**Issue by Jurgenn22** [thomasloven/lovelace-more-info-card#4] opened 2020-07-24 18:12 UTC
Hello,

This card no longer works under Home-Assistant version 0.113.0. I use this card a lot, now I have all empty cards on my frontend. Is it possible that the map will be updated?
Thank you, best regards,

Jurgen

**Comment by skynetforcats** [comment] 2020-07-27 10:38
Still does not in 113.1.

**Comment by mrfoxbit** [comment] 2020-07-29 07:03
Not working in 0.113.2

**Comment by dwainscheeren** [comment] 2020-07-30 10:45
Using the more info card inside a browser_mod popup also gives an empty/unloaded card.

**Comment by JAAlperin** [comment] 2020-07-30 21:49
I miss this functionality.  Hope it can be fixed, Thomas.  Thank you for all your fine contributions.

**Comment by liveware-problems** [comment] 2020-07-31 15:31
Running HA 0.113.2 and it's not showing for me either 👎 Hope it is an easy fix!

**Comment by chairstacker** [comment] 2020-08-02 23:30
Hi @thomasloven - just saw that you released an update yesterday and installed it via HACS.  
But even with upgrading HA to V0113.3 plus uninstalling and reinstalling the card, including 3 restarts, I can't get it to work.

**Comment by Jurgenn22** [comment] 2020-08-03 23:51
It's working again after the update for the card.

Thx!

**Comment by skynetforcats** [comment] 2020-08-04 09:13
> Hi @thomasloven - just saw that you released an update yesterday and installed it via HACS.
> But even with upgrading HA to V0113.3 plus uninstalling and reinstalling the card, including 3 restarts, I can't get it to work.

For me, only the title of the entity/card shows up.
Edit.: After a uninstall and then install again and using 'url /hacsfiles/lovelace-more-info-card/more-info-card.js' it works. (I had '/local/community/lovelace-more-info-card/more-info-card.js' from before)

**Comment by liveware-problems** [comment] 2020-08-04 10:40
Fix is working for me thanks @thomasloven - except for on an input_select where it says 'No More Info Available', any ideas on that?
![image](https://user-images.githubusercontent.com/32192569/89284804-3812ce00-d647-11ea-94c2-7ae5f7a87117.png)

**Comment by chairstacker** [comment] 2020-08-06 15:13
I figured out the my more-info-card still had an issue after the upgrade to the latest version in HACS because, at one time, it was installed manually so it still referred to the wrong, old js file.

Once I changed that, the more-info-card worked fine again.

Thanks @thomasloven for providing this card and updating it so that it works again with V0.113.x

**Comment by thomasloven** [comment] 2020-08-06 19:15
I'll close this issue as solved.
@liveware-problems, please open a new issue if your problem persists. Including an MWE.

**Closed as completed by thomasloven** 2020-08-06 19:15 UTC

**Comment by thomasloven** [comment] 2020-08-06 19:17
Also, duplicate of #3
